# Generated by Django 4.1.3 on 2022-11-27 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientesmodel',
            name='tipo_identificacion',
            field=models.CharField(choices=[('Selecciona una opción', ''), ('CC', 'Cédula de ciudadania'), ('CE', 'Cédula de extranjería'), ('PEP', 'Permiso especial de permanencia'), ('RC', 'Registro Civil'), ('TI', 'Tarjeta de Identidad'), ('V', 'Visa'), ('PP', 'Pasaporte')], max_length=4, verbose_name='Tipo de identificación'),
        ),
        migrations.AlterField(
            model_name='usuariosmodel',
            name='tipo_identificacion',
            field=models.CharField(choices=[('Selecciona una opción', ''), ('CC', 'Cédula de ciudadania'), ('CE', 'Cédula de extranjería'), ('PEP', 'Permiso especial de permanencia'), ('RC', 'Registro Civil'), ('TI', 'Tarjeta de Identidad'), ('V', 'Visa'), ('PP', 'Pasaporte')], max_length=4, verbose_name='Tipo de identificación'),
        ),
    ]
